version: '3'

services:
  db-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdata-test:/var/lib/postgresql/data
#   app-test:
#     build:
#       # TODO
#     ports:
#       - 127.0.0.1:3000:3000  # XXX temporary!!! involve HTTPS later.
#     # TODO potentially add `volumes` and `environment` fields

# volumes:
#   pgdata-test:
