FROM node:18.18-alpine3.17

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
COPY prisma ./prisma/

RUN npm i

COPY . .

ARG JWT
ENV JWT_SECRET $JWT

ARG DB_URL
ENV DATABASE_URL $DB_URL

ARG GOOGLE_API_KEY
ENV GOOGLE_TRANSLATE_API_KEY $GOOGLE_API_KEY

ARG ENV
ENV ENV $ENV

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

ARG AWS_IMAGES_BUCKET
ENV AWS_IMAGES_BUCKET $AWS_IMAGES_BUCKET

ARG TINDOORI_USE_LOCAL
ENV TINDOORI_USE_LOCAL $TINDOORI_USE_LOCAL

ARG POSTGRES_HOST
ENV POSTGRES_HOST $POSTGRES_HOST

ARG POSTGRES_PORT
ENV POSTGRES_PORT $POSTGRES_PORT

ARG POSTGRES_DB
ENV POSTGRES_DB $POSTGRES_DB

ARG POSTGRES_USER
ENV POSTGRES_USER $POSTGRES_USER

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD

ARG ONESIGNAL_API_KEY
ENV ONESIGNAL_API_KEY $ONESIGNAL_API_KEY

ARG ONESIGNAL_APP_ID
ENV ONESIGNAL_APP_ID $ONESIGNAL_APP_ID

ARG PORT
ENV PORT $PORT

CMD ["npm", "run", "start:migrate"]


