name: Run Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node 
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Install Deps (use legacy peer deps due to NPM bug with multer)
      run: npm install --legacy-peer-deps
    - name: Run ESLint
      run: npm run lint
